/*
 * Copyright (C) 2017 User
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package imageing;

import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.TitledBorder;

/**
 *
 * @author User
 */
public class txItem extends javax.swing.JPanel {

    /**
     * Creates new form txItem
     */
    public txItem() {
        initComponents();
        tagList.setCellRenderer(new txStockItemTagRenderer());
    }
    
public void setimage(String imgfilename){
     ImageIcon imageIcon = new ImageIcon(imgfilename);
     Image image = imageIcon.getImage();
     Image newimage = image.getScaledInstance(160, 120,  java.awt.Image.SCALE_SMOOTH);
     this.txitem_image.setIcon(new ImageIcon(newimage));
}    
public void setValues(TXStockImage item){
     this.txitem_image.setText(item.getNAME());
     this.setimage(item.getICONFILE());
     this.txitem_image.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), item.getNAME(),TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.CENTER));
     
     String last = item.getLASTTX();
     if (last == ""){
         this.lastTX.setText("necer sent");
     } else {
         this.lastTX.setText(last);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txitem_image = new javax.swing.JLabel();
        toTXButton = new javax.swing.JButton();
        maxSize = new javax.swing.JLabel();
        lastTX = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagList = new javax.swing.JList<>();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txitem_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageing/no-image_320.png"))); // NOI18N
        txitem_image.setBorder(javax.swing.BorderFactory.createTitledBorder("bordertitle"));

        toTXButton.setText("To TX");
        toTXButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toTXButtonMouseClicked(evt);
            }
        });
        toTXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTXButtonActionPerformed(evt);
            }
        });

        maxSize.setText("640x480");
        maxSize.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "max. size"));

        lastTX.setText("27.Dez.2017 ");
        lastTX.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "last TX"));

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageing/edit-icon-16.png"))); // NOI18N
        editButton.setToolTipText("");

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageing/trash-icon-16.png"))); // NOI18N
        deleteButton.setToolTipText("");

        tagList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tagList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        tagList.setValueIsAdjusting(true);
        tagList.setVisibleRowCount(2);
        jScrollPane1.setViewportView(tagList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txitem_image, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toTXButton)
                        .addContainerGap())
                    .addComponent(maxSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastTX, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toTXButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastTX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txitem_image, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toTXButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toTXButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_toTXButtonMouseClicked

    private void toTXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTXButtonActionPerformed
        System.out.println("imageing.txItem.toTXButtonActionPerformed()");  // TODO add your handling code here:
    }//GEN-LAST:event_toTXButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastTX;
    private javax.swing.JLabel maxSize;
    private javax.swing.JList<String> tagList;
    private javax.swing.JButton toTXButton;
    public javax.swing.JLabel txitem_image;
    // End of variables declaration//GEN-END:variables
}
